import { z } from 'zod';

export const reportSummarySchema = z.object({
  summaryText: z.string().describe("Concise 2-3 sentence clinical summary of the entire report"),
  criticalFindings: z.array(z.string()).optional().describe("List of critical or urgent findings requiring immediate attention"),
  reportGeneratedBy: z.string().describe("Clinician name or 'AI-Assisted Report Generation'"),
  reportDate: z.string().describe("Date report was generated in YYYY-MM-DD format"),
});

export type ReportSummaryProps = z.infer<typeof reportSummarySchema>;

export function ReportSummary({
  summaryText,
  criticalFindings,
  reportGeneratedBy,
  reportDate,
}: ReportSummaryProps) {
  return (
    <div className="bg-white border border-gray-300 rounded-xl p-6 shadow-md">
      <h2 className="text-xl font-semibold text-blue-600 border-b-2 border-blue-600 pb-2 mb-4">
        Report Summary
      </h2>
      
      <div className="mb-4">
        <p className="font-semibold text-gray-700">Clinical Summary:</p>
        <p className="text-gray-900 mt-1">{summaryText}</p>
      </div>

      {criticalFindings && criticalFindings.length > 0 && (
        <div className="bg-yellow-50 border-2 border-orange-400 rounded-lg p-4 mb-4">
          <h3 className="text-base font-bold text-orange-600 flex items-center gap-2">
            ⚠️ Critical Findings
          </h3>
          <ul className="list-disc list-inside mt-2 space-y-1">
            {criticalFindings.map((finding, idx) => (
              <li key={idx} className="text-red-700 font-medium">{finding}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="grid grid-cols-2 gap-4 text-sm">
        <div>
          <label className="text-xs font-semibold text-gray-600 uppercase">Report Generated By:</label>
          <p className="text-gray-900">{reportGeneratedBy}</p>
        </div>
        <div>
          <label className="text-xs font-semibold text-gray-600 uppercase">Report Date:</label>
          <p className="text-gray-900">{reportDate}</p>
        </div>
      </div>
    </div>
  );
}
